#!/usr/bin/with-contenv /bin/bash
set -e

# configure AWS credentials for the www-data user
aws="sudo -u www-data aws"

if [ "${AWS_PROFILE}" ] ; then
  profile="--profile ${AWS_PROFILE}"
fi

[ "${AWS_REGION}" ] && $aws $profile configure set region ${AWS_REGION}
[ "${AWS_ACCESS_KEY_ID}" ] && $aws $profile configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
[ "${AWS_SECRET_ACCESS_KEY}" ] && $aws $profile configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
